steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_IMAGE_API}', '-f', 'docker/Dockerfile.api', '.']
# Push the container image to Container Registry
images:
  - '${_IMAGE_API}'