name: Run Tests on PR to Main

on:
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PYTHON_VERSION: "3.10"

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3.5.3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v4.7.0
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'

    - name: Cache UV dependencies
      uses: actions/cache@v3.3.1
      with:
        path: |
          ~/.cache/uv
          .venv
        key: ${{ runner.os }}-uv-${{ hashFiles('**/pyproject.toml', '**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-uv-

    - name: Install UV
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Run tests with coverage
      run: |
        uv run pytest --cov-report xml:coverage.xml --cov=app 

    - name: Upload coverage report
      uses: codecov/codecov-action@v3.1.4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
        token: ${{ secrets.CODECOV_TOKEN }}